baseURL = "https://willearp.com/"
languageCode = "en-gb"
title = "willearp.com"
theme = "hugo-theme-console"
enableEmoji = true
summaryLength = 30
copyright = "Will Earp"

[params]

  [[params.navlinks]]
  name = "about/"
  url = "about/"
